### PR TITLE
Add/discourse with user tokens

### PR DESCRIPTION
**Pull request by vsoch**
This is a work in progress, adding the ability for a user to get his/her own token (discourse also under development to do this)

### CODE REVIEW

**Comment by vsoch** [comment]
With substantial help from [cfitz](https://gist.github.com/cfitz/4553167fe7fd9447145a901fe90986c2) we are ready for testing! And the updated docs are uploaded here.
[Discourse Helper _ HelpMe.pdf](https://github.com/vsoch/helpme/files/2713074/Discourse.Helper._.HelpMe.pdf)

**Comment by vsoch** [comment]
In that I can recruit some others to help test (and you have done enormous amounts already!) I'm going to merge, and if we have further issues we can still fix up :)

I don't know how to say thank you enough for your help - the work on discourse made this possible period, and you were a total pleasure to work with! Please ping me if I can ever help you too :)

**Comment by vsoch** [comment]
https://pypi.org/project/helpme/0.0.36/

**Comment by cfitz** [comment]
oh hey! 
sorry went back to my day job and got slammed...
yes, everything looked good to me. Tested it out and worked great!
Thanks again!

**Pull request merged**
